### ISSUE TITLE
Hubot workflows need converting from mistral to Orquesta

### ISSUE THREAD

**Issue by amanda11** [StackStorm-Exchange/stackstorm-hubot#10]
Mistral-v2 runner has been removed from the master branch, and will not be available in StackStorm 3.3.0 and above.

This pack has some mistral-v2 workflows that need updating to Orquesta workflows:

- post_result

**Comment by cyberkov** [comment]
Hello! 
I could be wrong, but I think this pack does not use mistral workflows. The mentioned action post_result is using a python script. Therefore I would suggest closing the issue.

Cheers Hannes

**Comment by amanda11** [comment]
@cyberkov you are completely correct, I will close.
